### PR TITLE
Sev snp enhancements v1

### PR DESCRIPTION
**Pull request by jraman567**
Hi there,

This pull request adds miscellaneous patches to address minor issues in computing the launch digest and formatting MetadataWrapper as a JSON.

Thank you!

### CODE REVIEW

**Comment by jraman567** [comment]
@derpsteb Hi there. Could you please confirm whether this pull request looks good? Thank you so much!

**Review by derpsteb — APPROVED** [review]
Awesome. Thanks for the patch. Couldn't test this but lgtm. Sorry for the delay, currently OOO. Feel free to merge.

**Comment by jraman567** [comment]
@derpsteb Thank you for approving!

The following commit conflicts with my pull request, and I just fixed it:
https://github.com/virtee/sev-snp-measure-go/commit/7ac59e8bc6812faeb56356f8d4e8edd56f829f27

**Review by derpsteb — APPROVED** [review]

**Comment by jraman567** [comment]
@derpsteb Could you please merge this pull request?

**Comment by derpsteb** [comment]
Closing this one as resolved by #5 .
I only realized now that I had "rebase and merge" selected and not "create merge commit". Thus, github rightfully complained that some commits are conflicting. 
Anyways. Hope it works now.

**Pull request closed without merging**
